/* Generated By:JavaCC: Do not edit this line. Token.java Version 6.0 */
/* JavaCCOptions:TOKEN_EXTENDS=,KEEP_LINE_COL=null,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

// Classe criada para representar os tokens de entrada que serão lidos da entrada padrão.

public class Token implements java.io.Serializable {

  // Identificador de versão desta classe serializavél.
  private static final long serialVersionUID = 1L;

  // Um inteiro que descreve o tipo desse token. Este sistema de numeração é determinado pelo JavaCCParser,
  // E uma tabela desses número está salva no arquivo de constantes (MiniJavaLexerConstants.java).
  public int kind;

  // O número da linha do primeiro carácter deste Token.
  public int beginLine;
  // O número da coluna do primeiro carácter deste Token.
  public int beginColumn;
  // O número da linha do último carácter deste Token.
  public int endLine;
  // O número da coluna do último carácter deste Token.
  public int endColumn;

 
  // A imagem do token (lexema).
  public String image;


  // Uma referência para o próximo token regular (não especial) da cadeia de entrada.
  // Se esse é o último token da cadeia de entrada, ou o analisador léxico não leu 
  // tokens além desse, esse campo é posto como null. Isso é verdade apenas se esse token 
  // é também um token regular. 
  public Token next;


  // Este campo é usado para acessar tokens especiais que ocorreram a priori deste token, mas 
  // depois do token regular (não especial) imediatamente anterior. Se não houver tais tokens
  // especiais, este campo será definido como nulo. Quando houver mais de um token especial, 
  // este campo se refere ao último desses tokens especiais, que por sua vez se refere ao próximo
  // token especial anterior por meio de seu campo specialToken, e assim por diante até o primeiro
  // token especial (cujo campo specialToken é nulo). Os campos next dos tokens especiais se referem
  // a outros tokens especiais que o seguem imediatamente (sem um token regular intermediário). Se
  // não houver tal token, este campo será nulo.
  public Token specialToken;

  /**
   * An optional attribute value of the Token.
   * Tokens which are not used as syntactic sugar will often contain
   * meaningful values that will be used later on by the compiler or
   * interpreter. This attribute value is often different from the image.
   * Any subclass of Token that actually wants to return a non-null value can
   * override this method as appropriate.
   */
  // Um valor de atributo opcional do Token.
  public Object getValue() {
    return null;
  }

  /**
   * No-argument constructor
   */
  public Token() {}

  /**
   * Constructs a new token for the specified Image.
   */
  public Token(int kind)
  {
    this(kind, null);
  }

  /**
   * Constructs a new token for the specified Image and Kind.
   */
  public Token(int kind, String image)
  {
    this.kind = kind;
    this.image = image;
  }

  /**
   * Returns the image.
   */
  public String toString()
  {
    return image;
  }

  /**
   * Returns a new Token object, by default. However, if you want, you
   * can create and return subclass objects based on the value of ofKind.
   * Simply add the cases to the switch for all those special cases.
   * For example, if you have a subclass of Token called IDToken that
   * you want to create if ofKind is ID, simply add something like :
   *
   *    case MyParserConstants.ID : return new IDToken(ofKind, image);
   *
   * to the following switch statement. Then you can cast matchedToken
   * variable to the appropriate type and use sit in your lexical actions.
   */
  public static Token newToken(int ofKind, String image)
  {
    switch(ofKind)
    {
      default : return new Token(ofKind, image);
    }
  }

  public static Token newToken(int ofKind)
  {
    return newToken(ofKind, null);
  }

}
/* JavaCC - OriginalChecksum=5d765304aa4132a76648767e2734d8b6 (do not edit this line) */
