/* Generated By:JavaCC: Do not edit this line. TokenMgrError.java Version 6.0 */

// Uma simples classe criada para tratar dos erros detectados pelo analisador léxico.

/** Token Manager Error. */
public class TokenMgrError extends Error
{

  // Identificador de versão desta classe serializavél.
  private static final long serialVersionUID = 1L;

  // As constantes seguintes fazem referência ao tipo de erro que pode ser lançado.

  // Ocorreu erro léxico
  static final int LEXICAL_ERROR = 0;

  // Uma tentativa foi feita de criar uma segunda instância de um gerenciador estático de token.
  static final int STATIC_LEXER_ERROR = 1;

  // Fora tentado alterar um estado léxico inválido.
  static final int INVALID_LEXICAL_STATE = 2;

  // Detectado (e resolvido) um loop infinito no gerenciador de token (analisador léxico). 
  static final int LOOP_DETECTED = 3;

  // Indica o porquê a exceção foi lançada. Ela conterá um dos 4 valores acima.
  int errorCode;

  // Substitui caracteres não imprimíveis pelas suas versões de escape (unicode escaped) equivalentes na dada string.
  protected static final String addEscapes(String str) {
    StringBuffer retval = new StringBuffer();
    char ch;
    for (int i = 0; i < str.length(); i++) {
      switch (str.charAt(i))
      {
        case 0 :
          continue;
        case '\b':
          retval.append("\\b");
          continue;
        case '\t':
          retval.append("\\t");
          continue;
        case '\n':
          retval.append("\\n");
          continue;
        case '\f':
          retval.append("\\f");
          continue;
        case '\r':
          retval.append("\\r");
          continue;
        case '\"':
          retval.append("\\\"");
          continue;
        case '\'':
          retval.append("\\\'");
          continue;
        case '\\':
          retval.append("\\\\");
          continue;
        default:
          if ((ch = str.charAt(i)) < 0x20 || ch > 0x7e) {
            String s = "0000" + Integer.toString(ch, 16);
            retval.append("\\u" + s.substring(s.length() - 4, s.length()));
          } else {
            retval.append(ch);
          }
          continue;
      }
    }
    return retval.toString();
  }

  /**
   * Retorna uma mensagem detalhada para o erro quando esse é lançado pelo analisador léxico, 
   * indicando um erro léxico.
   * Parâmetros:
   *    EOFSeen     : Indica se EOF causou o erro léxico
   *    curLexState : Estado léxico a qual esse erro ocorreu
   *    errorLine   : Número da linha onde o erro ocorreu
   *    errorColumn : Número da coluna onde o erro ocorreu
   *    errorAfter  : Prefixo que fora visto antes deste erro ocorrer
   *    curchar     : O carácter estranho
   */
  protected static String LexicalError(boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar) {
    return("Lexical error at line " +
          errorLine + ", column " +
          errorColumn + ".  Encountered: " +
          (EOFSeen ? "<EOF> " : ("\"" + addEscapes(String.valueOf(curChar)) + "\"") + " (" + (int)curChar + "), ") +
          "after : \"" + addEscapes(errorAfter) + "\"");
  }

  // Mensagem detalhada de erro
  public String getMessage() {
    return super.getMessage();
  }

// Métodos construtores de diferentes formatos

  // Sem argumentos
  public TokenMgrError() {
  }

  // Com mensagem e razão
  public TokenMgrError(String message, int reason) {
    super(message);
    errorCode = reason;
  }

  // Completo
  public TokenMgrError(boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar, int reason) {
    this(LexicalError(EOFSeen, lexState, errorLine, errorColumn, errorAfter, curChar), reason);
  }
}
/* JavaCC - OriginalChecksum=4eed931ea14d3450c6d5e22c7ba353d9 (do not edit this line) */
